version: "3.1"
services:
    app:
        build:
            context: ./../
            dockerfile: docker/${DOCKERFILE}
        environment:
            - PORT=${PORT}
        ports:
            - "${PORT}:${PORT}"
