version: "3.1"
services:
    app:
        build:
            context: ./../
            dockerfile: docker/${DOCKERFILE}
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - /usr/src/app/node_modules
            - /usr/src/app/.next
            - ./../:/usr/src/app
